import tkinter
from _overlapped import NULL
root=tkinter.Tk()
#futureValue = investmentAmount * (1 + monthlyInterestRate) years* 12
def calc():
    f=investment.get()*((1+interest.get()/1200)**(years.get()*12))
    l5.config(text=round(f,2))
investment=tkinter.DoubleVar()
interest=tkinter.DoubleVar()
years=tkinter.DoubleVar()
l1=tkinter.Label(root,text="Invest Amount")
e1=tkinter.Entry(root,textvariable=investment)
l2=tkinter.Label(root,text="Monthly interest rate")
e2=tkinter.Entry(root,textvariable=interest)
l3=tkinter.Label(root,text="Years")
e3=tkinter.Entry(root,textvariable=years)
l4=tkinter.Label(root,text="Future value")
l5=tkinter.Label(root)
b=tkinter.Button(root,text="calculate",command=calc)
l1.grid(row=0,column=0)
e1.grid(row=0,column=1)
l2.grid(row=1,column=0)
e2.grid(row=1,column=1)
l3.grid(row=2,column=0)
e3.grid(row=2,column=1)
l4.grid(row=3,column=0)
l5.grid(row=3,column=1)
b.grid(row=4,column=1)
root.mainloop()